# Copyright 2013-2014, Simon Kennedy, code@sffjunkie.co.uk
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Part of 'hiss' the asynchronous notification library

import hashlib
from os import urandom
from binascii import hexlify, unhexlify

from hiss.exception import HissValidationError

DEFAULT_HASH_ALGORITHM = 'SHA256'

class HashInfo():
    """Records the hash information required to be sent to remote hosts.

    :param algorithm: The algorithm used to generate the hash
    :type algorithm:  str
    :param key_hash:  The hash of the key. Generated by the hash algorithm
    :type key_hash:   bytes
    :param salt:      The salt added to the key to generate the key_hash
    :type salt:       bytes
    """

    def __init__(self, algorithm, key_hash, salt):
        self._algorithm = None
        self._key_hash = None
        self._salt = None
    
        self.algorithm = algorithm
        self.key_hash = key_hash
        self.salt = salt

    @property
    def algorithm(self):
        """Hash algorithm. One of MD5, SHA1 or SHA256"""
        
        return self._algorithm
    
    @algorithm.setter
    def algorithm(self, value):
        if isinstance(value, (bytes, bytearray)):
            value = value.decode('UTF-8')
        value = value.upper()
        
        if value not in ['MD5', 'SHA1', 'SHA256']:
            raise HissValidationError('Unknown hash algorithm %s specified.' % value)
        
        self._algorithm = value

    @property
    def key_hash(self):
        """algorithm(password + salt)"""
        
        return self._key_hash
    
    @key_hash.setter
    def key_hash(self, value):
        if isinstance(value, str):
            value = unhexlify(value.encode('UTF-8'))
        self._key_hash = value

    @property
    def salt(self):
        """Salt used to compute the key_hash."""
        
        return self._salt
    
    @salt.setter
    def salt(self, value):
        if isinstance(value, str):
            value = unhexlify(value.encode('UTF-8'))
        self._salt = value

    def __eq__(self, other):
        return self.algorithm == other.algorithm and \
            self.key_hash == other.key_hash and \
            self.salt == other.salt

    def __repr__(self):
        return '%s:%s.%s' % (self.algorithm,
                             hexlify(self.key_hash).decode('UTF-8'),
                             hexlify(self.salt).decode('UTF-8'))


def generate_hash(password, hash_algorithm=DEFAULT_HASH_ALGORITHM):
    """Create a :class:`~hiss.hash.HashInfo` instance for the password using
    the specified hash algorithm.

    :param password:       The password to generate the hash for.
    :type password:        str or UTF-8 encoded bytes.
    :param hash_algorithm: The algorithm to use to generate the hash (one of
                           `MD5`, `SHA1`, `SHA256` (default) or `SHA512`)
    :type hash_algorithm:  str
    :raises HissError:     if the hash_algorithm specified is not known
    """

    if hash_algorithm not in ['MD5', 'SHA1', 'SHA256', 'SHA512']:
        raise HissValidationError("Don't know how to handle hash algorithm %s" % hash_algorithm)

    if isinstance(password, str):
        password = password.encode('UTF-8')

    salt = urandom(16)
    key_basis = password + salt

    if hash_algorithm == 'MD5':
        key = hashlib.md5(key_basis).digest()
        key_hash = hashlib.md5(key).digest()
    elif hash_algorithm == 'SHA1':
        key = hashlib.sha1(key_basis).digest()
        key_hash = hashlib.sha1(key).digest()
    elif hash_algorithm == 'SHA256':
        key = hashlib.sha256(key_basis).digest()
        key_hash = hashlib.sha256(key).digest()
    elif hash_algorithm == 'SHA512':
        key = hashlib.sha512(key_basis).digest()
        key_hash = hashlib.sha512(key).digest()

    return HashInfo(DEFAULT_HASH_ALGORITHM, key_hash, salt)

def validate_hash(password, hash_to_validate):
    """Validate the information stored in the :class:`~hiss.hash.HashInfo`
    instance against the password.

    :param password:         The password used to validate the hash.
    :type password:          str or UTF-8 encoded bytes.
    :param hash_to_validate: The hash to validate
    :type hash_to_validate:  :class:`~hiss.hash.HashInfo`
    :raises HissError:       if the hash validation fails.
    """

    if hash_to_validate.algorithm not in ['MD5', 'SHA1', 'SHA256', 'SHA512']:
        raise ValueError("Don't know how to validate hash algorithm %s" % hash_to_validate.algorithm)

    if isinstance(password, str):
        password = password.encode('UTF-8')

    key_basis = password + hash_to_validate.salt

    if hash_to_validate.algorithm == 'MD5':
        key = hashlib.md5(key_basis).digest()
        key_hash = hashlib.md5(key).digest()
    elif hash_to_validate.algorithm == 'SHA1':
        key = hashlib.sha1(key_basis).digest()
        key_hash = hashlib.sha1(key).digest()
    elif hash_to_validate.algorithm == 'SHA256':
        key = hashlib.sha256(key_basis).digest()
        key_hash = hashlib.sha256(key).digest()
    elif hash_to_validate.algorithm == 'SHA512':
        key = hashlib.sha512(key_basis).digest()
        key_hash = hashlib.sha512(key).digest()

    if hash_to_validate.key_hash != key_hash:
        raise HissValidationError('Invalid hash in request') 
